// JavaScript Document

var provTxt = location.search.substr(1);//alert(provTxt);

switch(provTxt) {
	
	case '01'://principe feliz
		$('#boxFrases').append('<div class="sepFrase disBlock floatNone"></div> «La generosidad consiste en dar antes de que se nos pida.» <div class="fraseNombre disBlock floatNone">Proverbio árabe</div> <div class="sepFrase disBlock floatNone"></div>  «De todas las variedades de virtud, la generosidad es la más estimada.» <div class="fraseNombre disBlock floatNone">Proverbio árabe</div> <div class="sepFrase disBlock floatNone"></div>  «La falta de generosidad al vencer disminuye el mérito y los frutos de la victoria.» <div class="fraseNombre disBlock floatNone">Giuseppe Mazzini</div> <div class="sepFrase disBlock floatNone"></div>  «Sabiduría es saber el camino correcto… Integridad es tomarlo.» <div class="fraseNombre disBlock floatNone">M.H. Mckee</div> <div class="sepFrase disBlock floatNone"></div>  «El hombre justo no es el que no comete ninguna injusticia, sino el que, pudiendo ser injusto, no quiere serlo.» <div class="fraseNombre disBlock floatNone">Menandro</div> <div class="sepFrase disBlock floatNone"></div>  «Mejor que el hombre que sabe lo que es justo es el hombre que ama lo justo.» <div class="fraseNombre disBlock floatNone">Confucio</div> <div class="sepFrase disBlock floatNone"></div>');
	break;
	
	case '02'://la bella y la bestia
		$('#boxFrases').append('<div class="sepFrase disBlock floatNone"></div> «La verdadera humildad consiste en estar satisfecho.» <div class="fraseNombre disBlock floatNone">Henry F. Amiel</div> <div class="sepFrase disBlock floatNone"></div> «Si no tienes la libertad interior, ¿qué otra libertad esperas poder tener?» <div class="fraseNombre disBlock floatNone">Arturo Graf</div> <div class="sepFrase disBlock floatNone"></div> «La amabilidad es como una almohadilla, que aunque no tenga nada por dentro, por lo menos amortigua los embates de la vida.» <div class="fraseNombre disBlock floatNone">Arthur Schopenhauer</div> <div class="sepFrase disBlock floatNone"></div> «Si el hombre no debe ahogar sus sentimientos, tendrá entonces que practicar la amabilidad hacia los animales, ya que aquel que es cruel con los animales se vuelve tosco en su trato con los hombres. Se puede juzgar el corazón de un hombre por su trato a los animales.» <div class="fraseNombre disBlock floatNone">Immanuel Kant</div> <div class="sepFrase disBlock floatNone"></div> «Con palabras agradables y un poco de amabilidad se puede arrastrar a un elefante de un cabello.» <div class="fraseNombre disBlock floatNone">Proverbio Persa</div> <div class="sepFrase disBlock floatNone"></div> «Los más generosos acostumbran ser los más humildes.» <div class="fraseNombre disBlock floatNone">René Descartes</div> <div class="sepFrase disBlock floatNone"></div>');
	break;
	
	case '03'://pulgarcito
		$('#boxFrases').append('<div class="sepFrase disBlock floatNone"></div> «Muchas personas pasan por nuestra vida pero solo muy pocas llegan a ocupar un gran lugar en nuestro corazón.» <div class="fraseNombre disBlock floatNone">Adam Smith</div> <div class="sepFrase disBlock floatNone"></div> «Lo que somos se lo debemos al afecto. Los días de nuestra existencia ocurren gracias al cariño.» <div class="fraseNombre disBlock floatNone">Dalai Lama</div> <div class="sepFrase disBlock floatNone"></div> «Yo hago lo que usted no puede y usted hace lo que yo no puedo. Juntos podemos hacer grandes cosas.» <div class="fraseNombre disBlock floatNone">Madre Teresa de Calcuta</div> <div class="sepFrase disBlock floatNone"></div> «Con favores se conquista a los espíritus pequeños; a los nobles se les gana con afecto.» <div class="fraseNombre disBlock floatNone">Jenofonte</div> <div class="sepFrase disBlock floatNone"></div> «Solo los buenos sentimientos pueden unirnos, el interés jamás ha forjado uniones duraderas.» <div class="fraseNombre disBlock floatNone">Auguste Comte</div> <div class="sepFrase disBlock floatNone"></div> «La familia es base de la sociedad y el lugar donde las personas aprenden por vez primera los valores que les guían durante toda su vida.» <div class="fraseNombre disBlock floatNone">Juan Pablo II</div> <div class="sepFrase disBlock floatNone"></div> «No habléis nunca de un afecto malgastado. Un afecto jamás fue baldío.» <div class="fraseNombre disBlock floatNone">Henry Wadsworth Longfellow</div>');
	break;
	
	case '04'://el abuelo y el nieto');
		$('#boxFrases').append('«Siempre es más valioso tener el respeto que la admiración de las personas.» <div class="fraseNombre disBlock floatNone">Jean Jacques Rousseau</div> <div class="sepFrase disBlock floatNone"></div> «Ante todo, respetaos a vosotros mismos.» <div class="fraseNombre disBlock floatNone">Pitágoras de Samos</div> <div class="sepFrase disBlock floatNone"></div> «Tolerancia significa disculpar los defectos de los demás; tacto, no reparar en ellos.» <div class="fraseNombre disBlock floatNone">Arthur Schnitzler</div> <div class="sepFrase disBlock floatNone"></div> «Teniendo respeto y reverencia por la vida, entramos en una relación espiritual con el mundo.» <div class="fraseNombre disBlock floatNone">Albert Schweitzer</div> <div class="sepFrase disBlock floatNone"></div> «El respeto al derecho ajeno es la paz.» <div class="fraseNombre disBlock floatNone">Benito Juárez</div> <div class="sepFrase disBlock floatNone"></div> «Si de veras llegásemos a poder comprender, ya no podríamos juzgar.» <div class="fraseNombre disBlock floatNone">André Malraux</div> <div class="sepFrase disBlock floatNone"></div> «Un mundo mejor nace sobre la base de la fe y la comprensión.» <div class="fraseNombre disBlock floatNone">Douglas MacArthur</div> <div class="sepFrase disBlock floatNone"></div> «Los niños han de tener mucha tolerancia con los adultos.» <div class="fraseNombre disBlock floatNone">Antoine de Saint-Exupéry</div>');
	break;
	
	case '05'://el gigante egoista
		$('#boxFrases').append('<div class="sepFrase disBlock floatNone"></div> «Hay un libro abierto siempre para todos los ojos: la naturaleza.» <div class="fraseNombre disBlock floatNone">Jean-Jacques Rousseau</div> <div class="sepFrase disBlock floatNone"></div> «Durante centenares de miles de años, el hombre luchó para abrirse un lugar en la naturaleza. Por primera vez en la historia de nuestra especie, la situación se ha invertido y hoy es indispensable hacerle un lugar a la naturaleza en el mundo del hombre.» <div class="fraseNombre disBlock floatNone">Santiago Kovadloff</div> <div class="sepFrase disBlock floatNone"></div> «Si supiera que el mundo se acaba mañana, yo hoy aún plantaría un árbol.» <div class="fraseNombre disBlock floatNone">Martin Luther King</div> <div class="sepFrase disBlock floatNone"></div> «El único deber es el deber de divertirse terriblemente.» <div class="fraseNombre disBlock floatNone">Oscar Wilde</div> <div class="sepFrase disBlock floatNone"></div> «Cuando bailas, tu objetivo no es ir a un lugar determinado de la pista. Es disfrutar cada paso del camino.» <div class="fraseNombre disBlock floatNone">Wayne Dyer</div> <div class="sepFrase disBlock floatNone"></div> «Nunca tuve un día de trabajo en mi vida, todo era diversión.» <div class="fraseNombre disBlock floatNone">Thomas A. Edison</div> <div class="sepFrase disBlock floatNone"></div> «El placer de leer es doble cuando se vive con otra persona con la que compartir los libros.» <div class="fraseNombre disBlock floatNone">Katherine Mansfield</div>');
	break;
	
	case '06'://la flor mas bonita
		$('#boxFrases').append('«Mejor que con palabras la sinceridad se muestra con acciones.» <div class="fraseNombre disBlock floatNone">William Shakespeare</div> <div class="sepFrase disBlock floatNone"></div> «La sinceridad no obliga a decirlo todo, sino  que lo que se diga sea lo que se piense.» <div class="fraseNombre disBlock floatNone">Ángel Ganivet</div> <div class="sepFrase disBlock floatNone"></div> «Este es el primer precepto de la amistad: pedir a los amigos solo lo honesto, y solo lo honesto hacer por ellos.» <div class="fraseNombre disBlock floatNone">Marco Tulio Cicerón</div> <div class="sepFrase disBlock floatNone"></div> «La disciplina es la parte más importante del éxito.» <div class="fraseNombre disBlock floatNone">Truman Capote</div> <div class="sepFrase disBlock floatNone"></div> «Nuestra conducta es la única prueba de la sinceridad de nuestro corazón.» <div class="fraseNombre disBlock floatNone">Charles Thomson Rees Wilson</div> <div class="sepFrase disBlock floatNone"></div> «El hombre honesto no teme la luz ni la oscuridad.» <div class="fraseNombre disBlock floatNone">Thomas Fuller</div> <div class="sepFrase disBlock floatNone"></div> «Ningún legado es tan rico como la honestidad.» <div class="fraseNombre disBlock floatNone">William Shakespeare</div> <div class="sepFrase disBlock floatNone"></div> «El buen humor es, en la mayoría de las personas alegres, el satisfactorio resultado de una tenaz disciplina.» <div class="fraseNombre disBlock floatNone">Edwin Percy Whipple</div>');
	break;
	
}//fin switch

// «.» <div class="fraseNombre disBlock floatNone">Autor</div> <div class="sepFrase disBlock floatNone"></div>